#library "dynamiclev"
#include "zcommon.acs"

script 3125 (VOID)
{
	if (CheckActorCeilingTexture(0, "TLITE6_5"))    GiveInventory("BDECLightCheckerRed", 1);
	if (CheckActorCeilingTexture(0, "TLITE6_6"))    GiveInventory("BDECLightCheckerOrange", 1);

}

script 3126 (VOID)
{
	if (CheckActorCeilingTexture(0, "TLITE6_4"))    GiveInventory("BDECLightCheckerOrange", 1);
	if (CheckActorCeilingTexture(0, "TLITE6_1"))    GiveInventory("BDECLightCheckerOrange", 1);
	
	if	(GetCvar( "vid_renderer") == 1) { 
		if (CheckActorfLOORTexture(0, "NUKAGE1"))    GiveInventory("BDECNukageChecker", 1);
		if (CheckActorfLOORTexture(0, "NUKAGE2"))    GiveInventory("BDECNukageChecker", 1);
		if (CheckActorfLOORTexture(0, "NUKAGE3"))    GiveInventory("BDECNukageChecker", 1);
		if (CheckActorfLOORTexture(0, "NUKAGE4"))    GiveInventory("BDECNukageChecker", 1);
	}
}

//DOOM E1M1 - Hangar
script "MapEnhancementE1M1" (VOID)
{
}

//DOOM E1M2 - Nuclear Plant
script "MapEnhancementE1M2" (VOID)
{
}

//DOOM E1M3 - Toxin Refinery
script 2093 (VOID)
{
}

//DOOM E1M4 - Command Control
script "MapEnhancementE1M4" (VOID)
{
}

//DOOM E1M5 - Phobos Labs
script "MapEnhancementE1M5" (VOID)
{
}

//DOOM E1M6 - Central Processing
script "MapEnhancementE1M6" (VOID)
{
}

//DOOM E1M7 - Computer Station
script "MapEnhancementE1M7" (VOID)
{
}

//DOOM E1M8 - Phobos Anomaly
script "MapEnhancementE1M8" (VOID)
{
}

//DOOM E1M9 - Military Base
script "MapEnhancementE1M9" (VOID)
{
}

//DOOM E2M2 - Containment Area
script "MapEnhancementE2M2" (VOID)
{
}

//DOOM E2M3 - Refinery
script "MapEnhancementE2M3" (VOID)
{
}

//DOOM E2M4 - Deimos Lab
script "MapEnhancementE2M4" (VOID)
{
}

//DOOM E2M5 - Command Center
script "MapEnhancementE2M5" (VOID)
{
}

script "MapEnhancementE2M6" (VOID)
{
}

script "MapEnhancementE2M7" (VOID)
{
}

script "MapEnhancementE2M8" (VOID)
{
}

script "MapEnhancementE3M1" (VOID)
{
}

script "MapEnhancementE3M2" (VOID)
{
}

script "MapEnhancementE3M3" (VOID)
{
}

script "MapEnhancementE3M4" (VOID)
{
}

script "MapEnhancementE3M5" (VOID)
{
}

script "MapEnhancementE3M6" (VOID)
{
}

script "MapEnhancementE3M7" (VOID)
{
}

script "MapEnhancementE3M8" (VOID)
{
}

//DOOM 2 MAP 01 - Entryway
script "MapEnhancementD2Map01" (VOID)
{
}

script "MapEnhancementD2Map03" (VOID)
{
}

//DOOM 2 MAP 05 - Waste Tunnels
script "MapEnhancementD2Map05" (VOID)
{
}

//DOOM 2 MAP 06 - Crusher
script "MapEnhancementD2Map06" (VOID)
{
}

//DOOM 2 MAP 07 - Dead Simple
script "MapEnhancementD2Map07" (VOID)
{
}

//DOOM 2 MAP 10 - Refueling Base
script "MapEnhancementD2Map10" (VOID)
{
}

//DOOM 2 MAP 09 - The Pit
script "MapEnhancementD2Map09" (VOID)
{
}

//DOOM 2 MAP 12 - The Factory
script "MapEnhancementD2Map12" (VOID)
{
}

//DOOM 2 MAP 13 - Downtown
script "MapEnhancementD2Map13" (VOID)
{
}

//DOOM 2 MAP 15 - Industrial Zone
script "MapEnhancementD2Map15" (VOID)
{
}

//DOOM 2 MAP 16 - Suburbs
script "MapEnhancementD2Map16" (VOID)
{
}

//DOOM 2 MAP 18 - Courtyard
script "MapEnhancementD2Map18" (VOID)
{
}

//DOOM 2 MAP 19 - Castle
script "MapEnhancementD2Map19" (VOID)
{
}

//DOOM 2 MAP 20 - Gotcha
script "MapEnhancementD2Map20" (VOID)
{
}

//DOOM 2 MAP 24 - The Chasm
script "MapEnhancementD2Map24" (VOID)
{
}

//DOOM 2 MAP 25 - Bloodfalls
script "MapEnhancementD2Map25" (VOID)
{
}

//DOOM 2 MAP 26 - Mines
script "MapEnhancementD2Map26" (VOID)
{
}

//DOOM 2 MAP 27 - Monster Condo
script "MapEnhancementD2Map27" (VOID)
{
}

//DOOM 2 MAP 28 - Spirit World
script "MapEnhancementD2Map28" (VOID)
{
}

//DOOM 2 MAP 30 - Icon Of Sin
script 230 (VOID)
{
}

//DOOM 2 MAP 31 - Wolfenstein / IDKFA
Script "MapEnhancementD2Map31" (VOID)
{
	Thing_Remove(54);
	delay(35);
}

//DOOM 2 MAP 32 - Wolfenstein / Grosse
Script "MapEnhancementD2Map32" (VOID)
{
	delay(1);
}
